[functions]
  directory = "netlify/functions"

[build]
    functions = "netlify/functions"
    publish = "public"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"